config/routes.rb
Rails.application.routes.draw do
	root 'lists#index'

	resources :lists, :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
	has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	@items = Item.all
  end

  def show
  	@item = Item.find([:id])
  end

  def new
  	@item = Item.new
  end

  def create
  	@item = Item.new(@item_params)
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
  	@lists = List.all
  end

  def show
  	@list = List.find(params[:id])
  end

  def new
  	@list = List.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/index.html.erb
<h1> ToDo: </h1>

<%= link_to 'New List Item', new_item_path %>
<%= link_to 'Edit List Item', new_item_path %>
<%= link_to 'Destroy List Item', new_item_path %>
	
	<ul>	
	<% @items.each do |item| %>
	<li>


	<h3> <%= item.title %> </h3>
	<p> Description: <%= item.description %> </p>

	<%= form_for item do |f| %>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
    <br />
    <%= f.submit %>
    <% end %>

    <%= link_to 'Show Details', item_path(item) %>

	</li>
	<% end %>
	</ul>

app/views/items/new.html.erb
<h1> Create New List Item </h1>
<br />

<%= form_for @item do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />

  <%= f.label :description %>
  <%= f.text_field :description %>
  <br />
  
  <%= f.label :completed %>
  <%= f.check_box :completed %>


  <%= f.submit %>
<% end %>

<br />
<%= link_to 'Main Page', items_path %>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoContinued</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1> All ToDo Lists </h1>
<% @lists.each do |list| %>
<ul>
	<%= list.title %>
	<%= list.date %>
	<%= list.completed %>
	<%= link_to 'Show List', list_path(list) %>
</ul>	
<% end %>	

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<div class='list-title'>
	<h1> <%= @list.title %> - </h1>
	<h3> <%= @list.date %> </h3>
	<%=  %>
</div>

<!-- # this doesnt make sense to me at all (plural and singular -->
<%= link_to 'All List Items', items_path(@items) %>